package commands;

public enum CommandType {

    CREATEPERSON,
    CREATETASK,
    CREATEBOARD,
    CREATETEAM,
    SHOWALLPEOPLE,
    SHOWPERSONCACTIVITY,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITYCOMMAND,
    ADDCOMMENTTOTASK,
    SHOWTEAMMEMBERS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CREATEANEWBOARDINATEAM, SHOWALLTEAMBOARDS, SHOWBOARDSACTIVITY, CHANGERATINGOFAFEEDBACK, CHANGESTATUSOFAFEEDBACK, ASSIGNTASKTOAPERSON, UNASSIGNTASKTOAPERSON, CHANGESTORYSTATUS
}
