package commands;

public enum CommandType {

    CREATEPERSON,
    CREATETASK,
    CREATEBOARD,
    CREATETEAM,
    SHOWALLPEOPLE,
    SHOWPERSONCACTIVITY,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITYCOMMAND,
    ADDCOMMENTTOTASK,
    SHOWTEAMMEMBERS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CHANGESTORYSTATUS
}
