package commands;

public enum CommandType {

    CREATEPERSON,
    CREATETASK,
    CTREATEBOARD,
    CREATETEAM,
    SHOWALLPEOPLE,
    SHOWPERSONCACTIVITY,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITYCOMMAND
}
