package commands.enums;

public enum CommandType {

    CREATEPERSON,
    CREATEBOARD,
    CREATETEAM,
    CREATEANEWBOARDINATEAM,
    CREATENEWBUGINBOARD,
    CREATENEWSTORYINBOARD,
    CREATENEWFEEDBACKINBOARD,
    SHOWALLPEOPLE,
    SHOWPERSONCACTIVITY,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITYCOMMAND,
    ADDCOMMENTTOTASK,
    SHOWTEAMMEMBERS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    SHOWALLTEAMBOARDS,
    SHOWBOARDSACTIVITY,
    CHANGERATINGOFAFEEDBACK,
    CHANGESTATUSOFAFEEDBACK,
    ASSIGNTASKTOAPERSON,
    UNASSIGNTASKTOAPERSON,
    CHANGESTORYSTATUS
}
