package commands.enums;

public enum CommandType {

    CREATEPERSON,
    EMPTY,
    CREATENEWBUGINBOARD,
    CREATENEWSTORYINBOARD,
    CREATENEWFEEDBACKINBOARD,
    CREATETEAM,
    CREATEANEWBOARDINATEAM,

    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CHANGESTORYSTATUS,
    CHANGERATINGOFAFEEDBACK,
    CHANGESTATUSOFAFEEDBACK,
    CHANGEPRIORITYOFABUG,
    CHANGESEVERITYOFABUG,
    CHANGESTATUSOFABUG,

    ADDCOMMENTTOTASK,
    ADDPERSONTOATEAM,
    ASSIGNTASKTOAPERSON,
    UNASSIGNTASKTOAPERSON,

    SHOTEAMSACTIVITYCOMMAND,
    SHOWALLPEOPLE,
    SHOWALLTEAMS,
    SHOWPERSONCACTIVITY,
    SHOWTEAMMEMBERS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDSACTIVITY,
}
